# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: |
        npm install

    - uses: yukiarrr/ios-build-action@v1.4.0
      with:
        project-path: ActionTest.xcodeproj
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        certificate-password : ${{ secrets.CERT_PW }}
        configuration : Release
        export-method: enterprise
        workspace-path: ActionTest.xcworkspace
        
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: /Users/runner/work/iOSActionTest/iOSActionTest/output.ipa
